edition = "2018"
empty_item_single_line = false
force_multiline_blocks = true
format_strings = true
match_block_trailing_comma = true
max_width = 80
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
report_fixme = "Always"
report_todo = "Always"
struct_field_align_threshold = 20
struct_lit_single_line = false
unstable_features = true
use_try_shorthand = true
version = "Two"
